name: benchmark_server
description: Benchmark server
version: 0.0.1-dev
homepage: https://github.com/PlugFox/dart-http-server-benchmark
repository: https://github.com/PlugFox/dart-http-server-benchmark
issue_tracker: https://github.com/PlugFox/dart-http-server-benchmark/issues

publish_to: none

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # HTTP Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Logger
  l: ^4.1.0-pre.1

  # Database
  #postgrest: ^1.3.3

  # Utilities
  args: ^2.4.2
  meta: ^1.8.0
  crypto: ^3.0.3
  stack_trace: ^1.11.1

dev_dependencies:
  # Testing
  test: ^1.24.4
  #mockito: ^5.4.2
  #test_process: ^2.1.0

  # Linting
  lints: ^2.1.1

  # Codegen
  build_runner: ^2.4.6